---
title: "R Notebook"
output: html_notebook
---
------------------------------------------------------------------------

### Imports de paquetes

```{r}
require(ggplot2)
require(data.table)
require(dplyr)
require(httr)
require(rvest)
require(xml2)
```

### Preprocesamiento

#### Archivos csv Vuelos
```{r}
files = list.files(pattern="*.csv")
viajes = do.call(rbind, lapply(files, fread, sep = ";"))
rm(files)
```

##### Algunos vuelos
```{r}
head(sample_n(viajes, 10))
```

#### Parte Wikipedia
```{r}
pag_wiki = read_html("https://en.wikipedia.org/wiki/List_of_airports_in_Argentina")
elem_tabla = html_element(pag_wiki, ".wikitable")

latitud = html_nodes(pag_wiki, css = '.latitude')
latitud = html_text(latitud)

longitud = html_nodes(pag_wiki, css = '.longitude')
longitud = html_text(longitud)

aeropuertos = html_table(elem_tabla)
aeropuertos = aeropuertos[c(-4,-6)] # Elimino IATA, Coordenadas
aeropuertos["latitud"] = latitud
aeropuertos["longitud"] = longitud

rm(list = c("pag_wiki", "elem_tabla", "latitud", "longitud")) #Esto es para que no queden variables sueltas
head(aeropuertos, 10)
```

